version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./credentials:/app/credentials
    environment:
      - SERPAPI_KEY=${SERPAPI_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GOOGLE_CREDENTIALS_FILE=${GOOGLE_CREDENTIALS_FILE}
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: